---
- name: Update OS package caches for Debian
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - os

- name: Update OS package caches for CentOS
  dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - os

- name: Update OS packages
  package:
    name: '*'
    state: latest
  tags:
    - os

- name: Set a hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname
  tags:
    - os
